// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_match_set_cpp
Rcpp::NumericVector get_match_set_cpp(List pop, NumericVector ti_cond);
RcppExport SEXP _RLCS_get_match_set_cpp(SEXP popSEXP, SEXP ti_condSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pop(popSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ti_cond(ti_condSEXP);
    rcpp_result_gen = Rcpp::wrap(get_match_set_cpp(pop, ti_cond));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RLCS_get_match_set_cpp", (DL_FUNC) &_RLCS_get_match_set_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RLCS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
