# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_match_set_cpp <- function(pop, ti_cond) {
    .Call(`_RLCS_get_match_set_cpp`, pop, ti_cond)
}

