# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_correct_set_cpp2 <- function(match_pop_actions, t_class) {
    .Call(`_RLCS_get_correct_set_cpp2`, match_pop_actions, t_class)
}

update_accuracy_cpp2 <- function(pop) {
    .Call(`_RLCS_update_accuracy_cpp2`, pop)
}

inc_param_count_cpp2 <- function(pop, param_name) {
    .Call(`_RLCS_inc_param_count_cpp2`, pop, param_name)
}

inc_match_and_correct_count_cpp2 <- function(match_pop, correct_set) {
    .Call(`_RLCS_inc_match_and_correct_count_cpp2`, match_pop, correct_set)
}

min_param_count_cpp <- function(pop, param_name) {
    .Call(`_RLCS_min_param_count_cpp`, pop, param_name)
}

mean_correct_count_cpp <- function(pop) {
    .Call(`_RLCS_mean_correct_count_cpp`, pop)
}

which_cpp <- function(x) {
    .Call(`_RLCS_which_cpp`, x)
}

which_valid_rules_cpp <- function(numerosities, lengths_fixed_bits) {
    .Call(`_RLCS_which_valid_rules_cpp`, numerosities, lengths_fixed_bits)
}

